### ISSUE TITLE
Failed to resolve: :truesdk-0.7-releasePartner

### ISSUE THREAD

**Issue by junaidTni** [truecaller/android-sdk#26]
i am trying to add truecaller sdk. but facing this the error "Failed to resolve: :truesdk-0.7-releasePartner".
google it alot but dont find the solution.help me please

**Comment by k28gaurav** [comment]
Download truesdk-0.7-releasePartner.aar file and add it to library and try to build.

**Comment by junaidTni** [comment]
thanks alot for your response. can please guide me about i authored the
thread. what does it mean

**Comment by tarunnickelfox** [comment]
Did you find truesdk-0.7-releasePartner.aar? If yes, please share the link

**Comment by k28gaurav** [comment]
@tarunnickelfox 
 https://developer.truecaller.com/for-mobile-apps
At below you will find sdk for android. You can download .aar file from there

**Comment by khemrajsharma** [comment]
Here is True Sdk (truesdk-0.7-releasePartner.aar ) for android 

https://developer.truecaller.com/truecallersdk-android-v07.zip

And documentation has wrong name for implementation use below line.

Use 

    implementation(name: "truesdk-v0.7-releasePartner", ext: "aar")

Instead of 

    implementation(name: "truesdk-0.7-releasePartner", ext: "aar")
