### ISSUE TITLE
Can not find truesdk-0.7-releasePartner in documentation or anywhere

### ISSUE THREAD

**Issue by khemrajsharma** [truecaller/android-sdk#27]
You guys are making us confused. 

>  the provided truesdk-0.7-releasePartner.aar file into your libs folder. Example path: /app/libs/

Did you provide a link to `truesdk-0.7-releasePartner.aar`? I searched a lot, but could not find `.aar` file.

Also in the thread https://github.com/truecaller/android-sdk/issues/26, this guy needs same .aar file. But you did not provide a link, but you guys provided documentation link. 

Can you please be specific, provide a link to `truesdk-0.7-releasePartner.aar`.

I am very much disappointed with your documentation.

**Comment by mcaabhay** [comment]
Hi KhemRaj,
You can find the aar file at the bottom of the given page:
https://developer.truecaller.com/for-mobile-apps
scroll to the end there is android/ios sdk at the footer.
Hope it helps you.
